
.PHONY: all clean

all:
	@echo "Building Primary Bootstrap"
	@make -C Primary

	@echo "Building Secondary Bootstrap"
	@make -C Secondary

	@echo "Done !!!"

clean:
	@echo "Cleaning Primary Bootstrap"
	@make -C Primary clean

	@echo "Cleaning Secondary Bootstrap"
	@make -C Secondary clean

	@echo "Done !!!"
