##===- projects/c6x-decoder/tools/Makefile ----------------------*- Makefile -*-===##

#
# Relative path to the top of the source tree.
#
LEVEL=..

#
# List all of the subdirectories that we will compile.
#
DIRS=c6x-decoder

include $(LEVEL)/Makefile.common
