##===- projects/c6x-decoder/lib/Makefile ------------------------*- Makefile -*-===##

#
# Relative path to the top of the source tree.
#
LEVEL=..

#
# List all of the subdirectories that we will compile.
#
DIRS=BinaryReader InstructionMultilister InstructionDecoder LLVMGenerator

include $(LEVEL)/Makefile.common
